# ARREGLOS Y CLASES

## Matrices


Es un arreglo que tiene m x n elementos

A = \begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn}
\end{bmatrix}

In [6]:
A= [[1,2,3], [4,5,6], [7,8,9]]
print (A)

#vamos a crear otra lista
B= [[21, 34, 40], [71,17,77], [78,81,28]]
print (A+B)

print (2*A)

A[0][1]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [78, 81, 28]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]


2

In [9]:
#vectores y listas

L = A[0]
M = B[0]

print (L)
print (M)

[1, 2, 3]
[21, 34, 40]


In [11]:
a = L[0]
b = M[0]

print (a+b)

a==1

22


True

In [13]:
#suma de vectores

len (L)== len (M)

SUMA =[L[0] + M[0],L[1]+M[1], L[2]+M[2]]

print (SUMA)


SUMA = [L[i]+ M[i] for i in range (3)]
SUMA

[22, 36, 43]


[22, 36, 43]

### CRACIÓN DE FUNCIONES GLOBALES
la funcion para crear funciones es `def` que se cierra con un debug ( `print` o `return`)

---


In [17]:
def Hola():
  print("hola me llamo mariana")



In [18]:
Hola()

hola me llamo mariana


In [19]:
def saludar(s,n):
  print (f"hola me llamo {s} y tengo {n} años")


In [22]:
saludar ("mariana", 18)

hola me llamo mariana y tengo 18 años


In [44]:

I = [i for i in range (10)]

def par(x):
  for x in range(len(I)):
    if x % 2 == 0:
      print(f"{x} es par")
    else:
      print(f"{x} es impar")

In [52]:
par(1)

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [54]:
def suma_vectorial (L,M):
  x= [L[i]+M[i] for i in range (len(L))]
  return x

In [56]:
L = [1,2,3]
M = [21,34,40]

suma_vectorial(L,M)


[22, 36, 43]

MODULOS O LIBREARIAS

In [58]:
import math
from math import sqrt, pi

In [59]:
sqrt(68)

8.246211251235321

In [60]:
pi

3.141592653589793

###EL MODULO NUMPY

la funcion `array`



In [61]:
import numpy as np

L_vector =np.array(L)
M_vector =np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [69]:
C= [9,1,1,1,2,1,1,18,1]
A = [10,2,2,2,3,2,2,19,2]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  1  1]
 [ 1  2  1]
 [ 1 18  1]]
[[10  2  2]
 [ 2  3  2]
 [ 2 19  2]]


In [70]:
C_matriz @ A_matriz

array([[94, 40, 22],
       [16, 27,  8],
       [48, 75, 40]])